#!/bin/sh

set -e

ENWL_GEOJSON="$1" # path to ENWL tender areas GeoJSON file
DATA_DIR="$(dirname "$0")/../static/data" # path to /data directory
TENDER_AREAS_GEOJSON="$DATA_DIR/tender-areas.geojson"

PRECISION="0.00001"

mapshaper \
    -i "$ENWL_GEOJSON" \
    -uniq 'this.properties.substation_name' \
    -filter '["Ardwick", "Bolton By Bowland", "Catterall Waterworks", "Coniston", "Frederick Rd BSP", "Marple", "Moss Side (Longsight)", "Settle"].indexOf(this.properties.substation_name) > -1' \
    -sort 'this.properties.substation_name' \
    -filter-fields 'substation_name' \
    -o precision="$PRECISION" "$TENDER_AREAS_GEOJSON"
