#!/bin/sh

set -e

ENWL_GEOJSON="$1" # path to ENWL tender areas GeoJSON file
DATA_DIR="$(dirname "$0")/../static/data" # path to /data directory

PRECISION="0.00001"

mapshaper \
    -i "$ENWL_GEOJSON" \
    -uniq 'this.properties.substation_name' \
    -filter '["Ardwick", "Bolton By Bowland", "Catterall Waterworks", "Chorley South", "Coniston", "Frederick Rd BSP", "Marple", "Moss Lane", "Moss Side (Leyland) & Seven Stars", "Moss Side (Longsight)", "Peel St", "Settle"].indexOf(this.properties.substation_name) > -1' \
    -filter-fields 'substation_name' \
    -o precision="$PRECISION" "$DATA_DIR/tender-areas.geojson"
