#!/bin/sh

set -e

ENWL_GEOJSON="$1" # path to ENWL tender areas GeoJSON file
DATA_DIR="$(dirname "$0")/../static/data" # path to /data directory

PRECISION="0.00001"

mapshaper \
    -i "$ENWL_GEOJSON" \
    -uniq 'this.properties.substation_name' \
    -filter '["Frederick Rd BSP", "Marple", "Moss Lane", "Moss Side (Longsight)"].indexOf(this.properties.substation_name) > -1' \
    -filter-fields 'substation_name' \
    -o precision="$PRECISION" "$DATA_DIR/tender-areas.geojson"
